/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cdc-enrollment`; params?: Router.UnknownInputParams; } | { pathname: `/cdc-overview`; params?: Router.UnknownInputParams; } | { pathname: `/cdc-programs`; params?: Router.UnknownInputParams; } | { pathname: `/ministries`; params?: Router.UnknownInputParams; } | { pathname: `/prayer-request`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/weddings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bible` | `/bible`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/give` | `/give`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kids` | `/kids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/worship` | `/worship`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cdc-enrollment`; params?: Router.UnknownOutputParams; } | { pathname: `/cdc-overview`; params?: Router.UnknownOutputParams; } | { pathname: `/cdc-programs`; params?: Router.UnknownOutputParams; } | { pathname: `/ministries`; params?: Router.UnknownOutputParams; } | { pathname: `/prayer-request`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/weddings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bible` | `/bible`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/give` | `/give`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/kids` | `/kids`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/worship` | `/worship`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/cdc-enrollment${`?${string}` | `#${string}` | ''}` | `/cdc-overview${`?${string}` | `#${string}` | ''}` | `/cdc-programs${`?${string}` | `#${string}` | ''}` | `/ministries${`?${string}` | `#${string}` | ''}` | `/prayer-request${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/weddings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bible${`?${string}` | `#${string}` | ''}` | `/bible${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/give${`?${string}` | `#${string}` | ''}` | `/give${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/kids${`?${string}` | `#${string}` | ''}` | `/kids${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/worship${`?${string}` | `#${string}` | ''}` | `/worship${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cdc-enrollment`; params?: Router.UnknownInputParams; } | { pathname: `/cdc-overview`; params?: Router.UnknownInputParams; } | { pathname: `/cdc-programs`; params?: Router.UnknownInputParams; } | { pathname: `/ministries`; params?: Router.UnknownInputParams; } | { pathname: `/prayer-request`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/weddings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bible` | `/bible`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/give` | `/give`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kids` | `/kids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/worship` | `/worship`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
